# -*- coding: utf-8 -*-
"""erasmith_task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Kfuj1HBIBK3ARuhov5FWSp6mTyK4-sC
"""

import pandas as pd

A = pd.read_csv('a.csv',sep=',')

B = pd.read_csv('b.csv', sep=',')

A.head()

B.head()

A.columns

B.columns

"""A-B"""

A[~A.device_type.isin(B.device_type)]

set(A['device_type']) - set(B['device_type'])

"""B-A"""

B[~B.device_name.isin(A.device_name)]

set(B['device_name']) - set(A['device_name'])

"""New CSV with desired fields"""

a = {
    'Organisation_Name':A['Organisation_Name'],
     'network_name': A['network_name'],
     'device_name': A['device_name'],
     'device_type': A['device_type']
}

frame = pd.DataFrame(a)

frame

frame.to_csv('new.csv', sep='\t')

